import os

AOAI_ENDPOINT = os.getenv("AOAI_ENDPOINT")
AOAI_API_KEY = os.getenv("AOAI_API_KEY")
AOAI_DEPLOY_GPT4O = os.getenv("AOAI_DEPLOY_GPT4O")
AOAI_DEPLOY_EMBED_3_LARGE = os.getenv("AOAI_DEPLOY_EMBED_3_LARGE")
AOAI_API_VERSION = os.getenv("AOAI_API_VERSION", "2024-02-01")

VECTORSTORE_PATH = os.getenv("VECTORSTORE_PATH", "vectorstore")

